// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://siuropzsgqgndkaycztv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpdXJvcHpzZ3FnbmRrYXljenR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MDMzNzYsImV4cCI6MjA2NDE3OTM3Nn0.2e_igOUQLtpOB93bi_Rt-abw9mKEo_vuhbn1ItcCT3U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);